# vim:ft=ansible:

- name: Clone dotfiles repository
  git: repo=https://github.com/Batbold-Gansukh/dotfiles.git
       dest={{ansible_env.HOME}}/.dotfiles
       accept_hostkey=yes
       clone=yes
- name: Run dotfiles configure file
  shell: "{{ansible_env.HOME}}/.dotfiles/configure"
